# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "The Social Developer"
description: > # this means to ignore newlines until "email:"
   Marcus Rowland - Senior PHP Developer @ GoProposal by Sage
   Through this blog, I hope to share some anecdotal stories and lessons I've learned!

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/profile.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Marcus Rowland'
author: 'Marcus Rowland'
author_image: "/assets/images/profile.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://linkedin.com/in/mrowland93/
    desc: Follow me on LinkedIn
    share_url:
    share_title:
    share_link:
#
#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:
